# Generated by Django 4.0.3 on 2022-03-06 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_food', to=settings.AUTH_USER_MODEL)),
                ('safe_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='projectpantryapi.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_tags', to='projectpantryapi.food')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_tags', to='projectpantryapi.tag')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='projectpantryapi.location'),
        ),
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='projectpantryapi.quantity'),
        ),
        migrations.AddField(
            model_name='food',
            name='safe_food',
            field=models.ManyToManyField(related_name='safe_list', through='projectpantryapi.SafeList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(related_name='foods', through='projectpantryapi.FoodTag', to='projectpantryapi.tag'),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL),
        ),
    ]
