# Generated by Django 4.0.3 on 2022-03-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectpantryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='label',
            new_name='title',
        ),
    ]
