# Generated by Django 4.0.3 on 2022-03-14 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projectpantryapi', '0002_rename_label_quantity_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='safe_food',
        ),
        migrations.AddField(
            model_name='food',
            name='safe_foods',
            field=models.ManyToManyField(related_name='safe_list', through='projectpantryapi.SafeFood', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SafeList',
        ),
        migrations.AddField(
            model_name='safefood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_food', to='projectpantryapi.food'),
        ),
        migrations.AddField(
            model_name='safefood',
            name='list_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_food', to=settings.AUTH_USER_MODEL),
        ),
    ]
